spring.application.name=auth-service

#Database Configuration
#TODO: Use environment variables for database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres_password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.flyway.enabled=true

#JWT Configuration
#TODO: Use environment variables for database configuration
jwt.key=q#iwgCIyiyA5tPaKVGE=FGdiG71rcIrf0TgFUveLOSap4-Uj$ySbqynpPl1nN7N05EOqI$idS2-58HXKhZd3XE_iSDMMSyPxf&NKJn8a1kAuRj3szBcN4B=F6RIig43SbT9SlbsKdY_Ci#4Mf5F78FBLx$ugn#D6n$o4MdmZfDmAC4Vkqc8A&KRCBOkVxp#AW#__--IjETe2XfwH7$AkOSK83xYhtjHB2$01N6_StnawuwH#ri9SUbzrc&B2OYtqk#=hiYOe02$mk8RYa5NC&Xh0jvy2xuMn8D0mnby6G67kv-SuJeAlpT$5R1O&_GdBEINfyXi5MmF6ezrB#mfPdoK0
jwt.expiration=900000
