spring.application.name=auth-service

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.flyway.enabled=true

# JWT Configuration
jwt.key=${JWT_SECRET_KEY:default_development_secret_key_change_me_in_production_environment_default_development_secret_key_change_me_in_production_environment}
jwt.expiration=${JWT_EXPIRATION:900000}

# Error Handling Configuration
server.error.include-message=always

# RabbitMQ Configuration
spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:localhost}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

server.port=8080