spring.application.name=notification-service

# RabbitMQ configuration
#TODO: Use environment variables for database configuration
spring.rabbitmq.addresses=jaragua.lmq.cloudamqp.com
spring.rabbitmq.username=svjmaxkk
spring.rabbitmq.password=CvdkAs2F0MyYbkZfhnltmAa6-CXfy5fc
spring.rabbitmq.virtual-host=svjmaxkk

server.port=8081