spring.application.name=notification-service

# RabbitMQ Configuration
spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:localhost}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

server.port=8081

# JavaMailSender SMTP Configuration
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:your-email@gmail.com}
spring.mail.password=${SMTP_PASSWORD:your-password-or-app-key}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true